# -*- coding: utf-8 -*-
"""Mental_Health_Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yVJZ4rJ-lRDAc733MvdVT4we4DHNJanC

#Data Loading
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('Raw Data Final.csv.csv')

print(f"Dataset loaded: {df.shape[0]} students, {df.shape[1]} columns")
print(f"Missing values: {df.isnull().sum().sum()}")

# Anxiety items (GAD-7, 7 items, scale 0-3)
ANXIETY_MAP = {
    df.columns[7]:  'A1_Nervous',
    df.columns[8]:  'A2_CantStopWorrying',
    df.columns[9]:  'A3_TroubleRelaxing',
    df.columns[10]: 'A4_Irritated',
    df.columns[11]: 'A5_WorriedTooMuch',
    df.columns[12]: 'A6_Restless',
    df.columns[13]: 'A7_AfraidAwful',
}

# Stress items (PSS-10, 10 items, scale 0-4)
STRESS_MAP = {
    df.columns[16]: 'S1_Upset',
    df.columns[17]: 'S2_CantControl',
    df.columns[18]: 'S3_NervousStressed',
    df.columns[19]: 'S4_CantCope',
    df.columns[20]: 'S5_Confident',
    df.columns[21]: 'S6_GoingMyWay',
    df.columns[22]: 'S7_ControlIrritations',
    df.columns[23]: 'S8_PerformanceOnTop',
    df.columns[24]: 'S9_Angered',
    df.columns[25]: 'S10_DifficultiesPiling',
}

# Depression items (PHQ-9, 9 items, scale 0-3)
DEPRESSION_MAP = {
    df.columns[28]: 'D1_NoInterest',
    df.columns[29]: 'D2_FeelingDown',
    df.columns[30]: 'D3_SleepProblems',
    df.columns[31]: 'D4_LowEnergy',
    df.columns[32]: 'D5_PoorAppetite',
    df.columns[33]: 'D6_FeelingBad',
    df.columns[34]: 'D7_PoorConcentration',
    df.columns[35]: 'D8_Psychomotor',
    df.columns[36]: 'D9_SuicidalThoughts',
}

ALL_ITEMS_MAP = {**ANXIETY_MAP, **STRESS_MAP, **DEPRESSION_MAP}

# Create clean symptom dataframe
symptoms = df[list(ALL_ITEMS_MAP.keys())].rename(columns=ALL_ITEMS_MAP).copy()

# Add labels and moderators
symptoms['Anxiety_Label']    = df['Anxiety Label']
symptoms['Stress_Label']     = df['Stress Label']
symptoms['Depression_Label'] = df['Depression Label']
symptoms['CGPA']             = df['6. Current CGPA']
symptoms['Scholarship']      = df['7. Did you receive a waiver or scholarship at your university?']
symptoms['Gender']           = df['2. Gender']
symptoms['Year']             = df['5. Academic Year']

# Define column groups
ANXIETY_COLS    = list(ANXIETY_MAP.values())
STRESS_COLS     = list(STRESS_MAP.values())
DEPRESSION_COLS = list(DEPRESSION_MAP.values())
SYMPTOM_COLS    = ANXIETY_COLS + STRESS_COLS + DEPRESSION_COLS

# Symptom-only dataframe (numeric only)
X = symptoms[SYMPTOM_COLS].copy()

print(f"\nSymptom matrix: {X.shape}")
print(f"Anxiety items:    {len(ANXIETY_COLS)}")
print(f"Stress items:     {len(STRESS_COLS)}")
print(f"Depression items: {len(DEPRESSION_COLS)}")
print(f"\nSeverity:")
print(f"  Severe Anxiety:    {(symptoms['Anxiety_Label']=='Severe Anxiety').sum()} ({(symptoms['Anxiety_Label']=='Severe Anxiety').mean()*100:.1f}%)")
print(f"  High Stress:       {(symptoms['Stress_Label']=='High Perceived Stress').sum()} ({(symptoms['Stress_Label']=='High Perceived Stress').mean()*100:.1f}%)")
print(f"  Severe Depression: {(symptoms['Depression_Label']=='Severe Depression').sum()} ({(symptoms['Depression_Label']=='Severe Depression').mean()*100:.1f}%)")

"""#Exploratory Analysis"""

import matplotlib.pyplot as plt
import seaborn as sns

# ---- 2A: Severity Distribution Bar Chart ----
fig, axes = plt.subplots(1, 3, figsize=(18, 6))
fig.suptitle('Mental Health Severity Distribution\nBangladeshi Private University Students (n=1,977)',
             fontsize=14, fontweight='bold')

# Anxiety
anxiety_order = ['Minimal Anxiety', 'Mild Anxiety', 'Moderate Anxiety', 'Severe Anxiety']
anxiety_counts = symptoms['Anxiety_Label'].value_counts().reindex(anxiety_order)
colors_a = ['#2ecc71', '#f1c40f', '#e67e22', '#e74c3c']
axes[0].bar(range(len(anxiety_order)), anxiety_counts.values, color=colors_a)
axes[0].set_xticks(range(len(anxiety_order)))
axes[0].set_xticklabels(['Minimal', 'Mild', 'Moderate', 'Severe'], rotation=15)
axes[0].set_title('Anxiety (GAD-7)', fontweight='bold')
axes[0].set_ylabel('Number of Students')
for i, v in enumerate(anxiety_counts.values):
    axes[0].text(i, v + 10, f'{v}\n({v/len(symptoms)*100:.1f}%)', ha='center', fontsize=9)

# Stress
stress_order = ['Low Stress', 'Moderate Stress', 'High Perceived Stress']
stress_counts = symptoms['Stress_Label'].value_counts().reindex(stress_order)
colors_s = ['#2ecc71', '#f1c40f', '#e74c3c']
axes[1].bar(range(len(stress_order)), stress_counts.values, color=colors_s)
axes[1].set_xticks(range(len(stress_order)))
axes[1].set_xticklabels(['Low', 'Moderate', 'High'], rotation=15)
axes[1].set_title('Stress (PSS-10)', fontweight='bold')
for i, v in enumerate(stress_counts.values):
    axes[1].text(i, v + 10, f'{v}\n({v/len(symptoms)*100:.1f}%)', ha='center', fontsize=9)

# Depression
dep_order = ['No Depression', 'Minimal Depression', 'Mild Depression',
             'Moderate Depression', 'Moderately Severe Depression', 'Severe Depression']
dep_counts = symptoms['Depression_Label'].value_counts().reindex(dep_order)
colors_d = ['#27ae60', '#2ecc71', '#f1c40f', '#e67e22', '#e74c3c', '#8e44ad']
axes[2].bar(range(len(dep_order)), dep_counts.values, color=colors_d)
axes[2].set_xticks(range(len(dep_order)))
axes[2].set_xticklabels(['None', 'Minimal', 'Mild', 'Moderate', 'Mod-Severe', 'Severe'], rotation=15)
axes[2].set_title('Depression (PHQ-9)', fontweight='bold')
for i, v in enumerate(dep_counts.values):
    axes[2].text(i, v + 5, f'{v}', ha='center', fontsize=8)

plt.tight_layout()
plt.savefig('fig1_severity_distribution.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig1_severity_distribution.png")

# ---- 2B: Mean Symptom Score Heatmap ----
fig, ax = plt.subplots(figsize=(14, 8))
mean_scores = X.mean().values.reshape(1, -1)
sns.heatmap(
    pd.DataFrame(mean_scores, columns=SYMPTOM_COLS),
    annot=True, fmt='.2f', cmap='RdYlGn_r',
    ax=ax, cbar_kws={'label': 'Mean Score'}
)
ax.set_title('Mean Symptom Item Scores Across All Students', fontweight='bold', fontsize=13)
ax.set_xticklabels(SYMPTOM_COLS, rotation=45, ha='right', fontsize=9)
ax.set_yticks([])
plt.tight_layout()
plt.savefig('fig2_mean_symptom_scores.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig2_mean_symptom_scores.png")

# ---- 2C: Symptom Score by Depression Severity ----
dep_groups = ['Mild Depression', 'Moderate Depression',
              'Moderately Severe Depression', 'Severe Depression']
group_means = []
for g in dep_groups:
    mask = symptoms['Depression_Label'] == g
    group_means.append(X[mask].mean())

mean_df = pd.DataFrame(group_means, index=['Mild', 'Moderate', 'Mod-Severe', 'Severe'])

fig, ax = plt.subplots(figsize=(16, 6))
mean_df.plot(kind='bar', ax=ax, colormap='RdYlGn_r', legend=False)
ax.set_title('Symptom Item Means Across Depression Severity Groups', fontweight='bold')
ax.set_xlabel('Depression Severity Group')
ax.set_ylabel('Mean Score')
ax.set_xticklabels(mean_df.index, rotation=0)
plt.tight_layout()
plt.savefig('fig3_symptoms_by_severity.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig3_symptoms_by_severity.png")

print("\nExploratory Analysis Complete")
print(f"Key statistic: {(symptoms['Depression_Label'].isin(['Severe Depression','Moderately Severe Depression'])).sum()} students ({(symptoms['Depression_Label'].isin(['Severe Depression','Moderately Severe Depression'])).mean()*100:.1f}%) show Severe or Moderately Severe Depression")

"""#Symptom Network Analysis"""

from scipy import stats
import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
from collections import defaultdict

# ---- 3A: Compute Spearman Correlation Matrix ----
corr_matrix = X.corr(method='spearman')

# ---- 3B: Build Network (threshold |r| > 0.30) ----
THRESHOLD = 0.30
G = nx.Graph()
G.add_nodes_from(SYMPTOM_COLS)

edges = []
for i, col1 in enumerate(SYMPTOM_COLS):
    for j, col2 in enumerate(SYMPTOM_COLS):
        if i < j:
            r = corr_matrix.loc[col1, col2]
            if abs(r) > THRESHOLD:
                G.add_edge(col1, col2, weight=abs(r), r=r)
                edges.append({'source': col1, 'target': col2, 'weight': abs(r), 'r': round(r, 3)})

edges_df = pd.DataFrame(edges).sort_values('weight', ascending=False)
print(f"Total significant edges (|r|>{THRESHOLD}): {len(edges_df)}")
print(f"Cross-domain edges: {len(edges_df[edges_df.source.str[0] != edges_df.target.str[0]])}")

# ---- 3C: Centrality Measures ----
degree_centrality    = nx.degree_centrality(G)
strength_centrality  = {n: sum(d['weight'] for _, _, d in G.edges(n, data=True)) for n in G.nodes()}
betweenness          = nx.betweenness_centrality(G, weight='weight')

centrality_df = pd.DataFrame({
    'symptom':     SYMPTOM_COLS,
    'degree':      [degree_centrality[n] for n in SYMPTOM_COLS],
    'strength':    [strength_centrality[n] for n in SYMPTOM_COLS],
    'betweenness': [betweenness[n] for n in SYMPTOM_COLS],
    'domain':      ['Anxiety' if n.startswith('A') else 'Stress' if n.startswith('S') else 'Depression'
                    for n in SYMPTOM_COLS]
}).sort_values('strength', ascending=False)

print("\nTop 10 Most Central Symptoms:")
print(centrality_df[['symptom', 'domain', 'strength', 'betweenness']].head(10).to_string(index=False))

# ---- 3D: Visualize Network ----
fig, ax = plt.subplots(1, 1, figsize=(16, 12))

# Color nodes by domain
node_colors = []
for n in G.nodes():
    if n.startswith('A'):
        node_colors.append('#3498db')   # Blue = Anxiety
    elif n.startswith('S'):
        node_colors.append('#e67e22')   # Orange = Stress
    else:
        node_colors.append('#e74c3c')   # Red = Depression

# Size by strength
node_sizes = [strength_centrality[n] * 200 for n in G.nodes()]

# Edge width by correlation strength
edge_widths = [G[u][v]['weight'] * 3 for u, v in G.edges()]

# Layout: group by domain
pos = {}
a_nodes = [n for n in SYMPTOM_COLS if n.startswith('A')]
s_nodes = [n for n in SYMPTOM_COLS if n.startswith('S')]
d_nodes = [n for n in SYMPTOM_COLS if n.startswith('D')]

for i, n in enumerate(a_nodes):
    pos[n] = (-3, i - len(a_nodes)/2)
for i, n in enumerate(s_nodes):
    pos[n] = (0, i - len(s_nodes)/2)
for i, n in enumerate(d_nodes):
    pos[n] = (3, i - len(d_nodes)/2)

# Draw cross-domain edges in different color
within_edges  = [(u, v) for u, v in G.edges() if u[0] == v[0]]
cross_edges   = [(u, v) for u, v in G.edges() if u[0] != v[0]]

nx.draw_networkx_edges(G, pos, edgelist=within_edges, width=1.5,
                       alpha=0.3, edge_color='gray', ax=ax)
nx.draw_networkx_edges(G, pos, edgelist=cross_edges, width=2.5,
                       alpha=0.7, edge_color='#9b59b6', ax=ax)
nx.draw_networkx_nodes(G, pos, node_color=node_colors,
                       node_size=node_sizes, alpha=0.9, ax=ax)
nx.draw_networkx_labels(G, pos, font_size=7, ax=ax)

# Legend
patches = [
    mpatches.Patch(color='#3498db', label='Anxiety (GAD-7)'),
    mpatches.Patch(color='#e67e22', label='Stress (PSS-10)'),
    mpatches.Patch(color='#e74c3c', label='Depression (PHQ-9)'),
    mpatches.Patch(color='#9b59b6', label='Cross-domain bridge'),
]
ax.legend(handles=patches, loc='upper right', fontsize=11)
ax.set_title('Academic Pressure Symptom Network\n26 Items, Spearman |r|>0.30, Node size = Centrality',
             fontweight='bold', fontsize=13)
ax.axis('off')
plt.tight_layout()
plt.savefig('fig4_symptom_network.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig4_symptom_network.png")

# ---- 3E: Top Cross-Domain Bridges ----
print("\nTop 15 Cross-Domain Bridge Connections:")
cross_df = edges_df[edges_df.source.str[0] != edges_df.target.str[0]].head(15)
print(cross_df[['source', 'target', 'r']].to_string(index=False))

"""#BAYESIAN NETWORK CAUSAL DISCOVERY"""

!pip install pgmpy

from pgmpy.estimators import HillClimbSearch
import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

print("Running Bayesian Network Structure Learning...")
print("Algorithm: Hill Climb Search | Score: BIC-G | Max indegree: 3")
print("This may take 2-5 minutes on Colab...")

hc = HillClimbSearch(data=X)
bn_model = hc.estimate(
    scoring_method='bic-g',
    show_progress=True,
    max_indegree=3,
    max_iter=1000
)

print(f"\nBayesian Network found: {len(bn_model.edges())} directed causal edges")

# Separate within-domain and cross-domain edges
all_edges     = list(bn_model.edges())
within_edges  = [(u, v) for u, v in all_edges if u[0] == v[0]]
cross_edges   = [(u, v) for u, v in all_edges if u[0] != v[0]]

print(f"Within-domain edges:  {len(within_edges)}")
print(f"Cross-domain edges:   {len(cross_edges)}")

print("\nCross-Domain Causal Edges (Most Important):")
for u, v in cross_edges:
    src = 'Anxiety' if u.startswith('A') else 'Stress' if u.startswith('S') else 'Depression'
    tgt = 'Anxiety' if v.startswith('A') else 'Stress' if v.startswith('S') else 'Depression'
    print(f"  {u} [{src}] → {v} [{tgt}]")

# ---- Visualize Bayesian Network ----
G_bn = nx.DiGraph()
G_bn.add_edges_from(all_edges)

fig, ax = plt.subplots(figsize=(18, 12))

a_nodes = [n for n in SYMPTOM_COLS if n.startswith('A') and n in G_bn.nodes()]
s_nodes = [n for n in SYMPTOM_COLS if n.startswith('S') and n in G_bn.nodes()]
d_nodes = [n for n in SYMPTOM_COLS if n.startswith('D') and n in G_bn.nodes()]

pos = {}
for i, n in enumerate(a_nodes):
    pos[n] = (-4, i * 1.2 - len(a_nodes)/2)
for i, n in enumerate(s_nodes):
    pos[n] = (0, i * 1.2 - len(s_nodes)/2)
for i, n in enumerate(d_nodes):
    pos[n] = (4, i * 1.2 - len(d_nodes)/2)

node_colors = []
for n in G_bn.nodes():
    if n.startswith('A'):   node_colors.append('#3498db')
    elif n.startswith('S'): node_colors.append('#e67e22')
    else:                   node_colors.append('#e74c3c')

# Draw edges
nx.draw_networkx_edges(G_bn, pos, edgelist=within_edges,
    arrows=True, arrowsize=20, width=1.5,
    edge_color='gray', alpha=0.4,
    connectionstyle='arc3,rad=0.1', ax=ax)
nx.draw_networkx_edges(G_bn, pos, edgelist=cross_edges,
    arrows=True, arrowsize=25, width=3,
    edge_color='#9b59b6', alpha=0.85,
    connectionstyle='arc3,rad=0.15', ax=ax)

nx.draw_networkx_nodes(G_bn, pos, node_color=node_colors,
    node_size=1200, alpha=0.9, ax=ax)
nx.draw_networkx_labels(G_bn, pos, font_size=7, ax=ax)

# Domain labels
for x_pos, label in [(-4, 'ANXIETY\n(GAD-7)'), (0, 'STRESS\n(PSS-10)'), (4, 'DEPRESSION\n(PHQ-9)')]:
    ax.text(x_pos, 6.5, label, ha='center', fontsize=13, fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.3',
                      facecolor='#3498db' if 'ANXIETY' in label else '#e67e22' if 'STRESS' in label else '#e74c3c',
                      alpha=0.3))

patches = [
    mpatches.Patch(color='#3498db', label='Anxiety'),
    mpatches.Patch(color='#e67e22', label='Stress'),
    mpatches.Patch(color='#e74c3c', label='Depression'),
    mpatches.Patch(color='#9b59b6', label='Cross-domain causal edge'),
]
ax.legend(handles=patches, loc='lower right', fontsize=11)
ax.set_title('Bayesian Network: Causal Structure of Academic Pressure Symptoms\n'
             'Purple arrows = causal pathways between domains',
             fontweight='bold', fontsize=13)
ax.axis('off')
plt.tight_layout()
plt.savefig('fig5_bayesian_network.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig5_bayesian_network.png")

# ---- Save edges for later use ----
import json
with open('bayesian_edges.json', 'w') as f:
    json.dump(all_edges, f)
print("Saved: bayesian_edges.json")

# Add this to your Step 6 cell instead of NOTEARS
# Bootstrap stability analysis for Bayesian Network edges

from pgmpy.estimators import HillClimbSearch
import numpy as np

print("Bootstrap stability analysis (50 iterations)...")
edge_counts = {}
n_bootstrap = 50

for i in range(n_bootstrap):
    sample = X.sample(frac=0.8, replace=True, random_state=i)
    hc = HillClimbSearch(data=sample)
    model = hc.estimate(scoring_method='bic-g', show_progress=False,
                       max_indegree=3, max_iter=500)
    for edge in model.edges():
        edge_counts[edge] = edge_counts.get(edge, 0) + 1

# Stable edges (appear in >60% of bootstrap samples)
stable_edges = {e: c for e, c in edge_counts.items() if c/n_bootstrap > 0.60}
print(f"\nStable edges (>60% bootstrap): {len(stable_edges)}")
for edge, count in sorted(stable_edges.items(), key=lambda x: x[1], reverse=True):
    cross = " [CROSS]" if edge[0][0] != edge[1][0] else ""
    print(f"  {edge[0]} → {edge[1]}: {count/n_bootstrap*100:.0f}%{cross}")

"""#PC ALGORITHM CAUSAL DISCOVERY"""

from pgmpy.estimators import PC
import json

print("Running PC Algorithm (fast variant, max_cond_vars=3)...")
print("Limiting conditioning set size to make it tractable...")

pc_estimator = PC(data=X)
pc_model = pc_estimator.estimate(
    variant="stable",
    significance_level=0.05,
    show_progress=True,
    max_cond_vars=3,
    return_type="dag"
)

print(f"PC Algorithm found: {len(pc_model.edges())} edges")
pc_all_edges   = list(pc_model.edges())
pc_cross_edges = [(u,v) for u,v in pc_all_edges if u[0] != v[0]]

print(f"Cross-domain edges: {len(pc_cross_edges)}")
print("\nPC Cross-Domain Edges:")
for u, v in pc_cross_edges:
    print(f"  {u} → {v}")

with open('pc_edges.json', 'w') as f:
    json.dump(pc_all_edges, f)
print("Saved: pc_edges.json")

import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import json

# Load the PC algorithm edges
with open('pc_edges.json', 'r') as f:
    pc_all_edges = json.load(f)

# Create a directed graph
G_pc = nx.DiGraph()
G_pc.add_edges_from(pc_all_edges)

fig, ax = plt.subplots(figsize=(18, 12))

# Define node groups by domain for consistent layout
a_nodes = [n for n in SYMPTOM_COLS if n.startswith('A') and n in G_pc.nodes()]
s_nodes = [n for n in SYMPTOM_COLS if n.startswith('S') and n in G_pc.nodes()]
d_nodes = [n for n in SYMPTOM_COLS if n.startswith('D') and n in G_pc.nodes()]

# Position nodes by domain (similar to Bayesian Network plot)
pos = {}
for i, n in enumerate(a_nodes):
    pos[n] = (-4, i * 1.2 - len(a_nodes)/2)
for i, n in enumerate(s_nodes):
    pos[n] = (0, i * 1.2 - len(s_nodes)/2)
for i, n in enumerate(d_nodes):
    pos[n] = (4, i * 1.2 - len(d_nodes)/2)

# Color nodes by domain
node_colors = []
for n in G_pc.nodes():
    if n.startswith('A'):   node_colors.append('#3498db')  # Anxiety (Blue)
    elif n.startswith('S'): node_colors.append('#e67e22')  # Stress (Orange)
    else:                   node_colors.append('#e74c3c')  # Depression (Red)

# Separate within-domain and cross-domain edges for different styling
pc_within_edges  = [(u, v) for u, v in pc_all_edges if u[0] == v[0]]
pc_cross_edges   = [(u, v) for u, v in pc_all_edges if u[0] != v[0]]

# Draw within-domain edges
nx.draw_networkx_edges(G_pc, pos, edgelist=pc_within_edges,
    arrows=True, arrowsize=20, width=1.5,
    edge_color='gray', alpha=0.4,
    connectionstyle='arc3,rad=0.1', ax=ax)

# Draw cross-domain edges
nx.draw_networkx_edges(G_pc, pos, edgelist=pc_cross_edges,
    arrows=True, arrowsize=25, width=3,
    edge_color='#9b59b6', alpha=0.85, # Purple for cross-domain
    connectionstyle='arc3,rad=0.15', ax=ax)

# Draw nodes and labels
nx.draw_networkx_nodes(G_pc, pos, node_color=node_colors,
    node_size=1200, alpha=0.9, ax=ax)
nx.draw_networkx_labels(G_pc, pos, font_size=7, ax=ax)

# Add domain labels (similar to Bayesian Network plot)
for x_pos, label in [(-4, 'ANXIETY\n(GAD-7)'), (0, 'STRESS\n(PSS-10)'), (4, 'DEPRESSION\n(PHQ-9)')]:
    ax.text(x_pos, 6.5, label, ha='center', fontsize=13, fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.3',
                      facecolor='#3498db' if 'ANXIETY' in label else '#e67e22' if 'STRESS' in label else '#e74c3c',
                      alpha=0.3))

# Create a legend
patches = [
    mpatches.Patch(color='#3498db', label='Anxiety'),
    mpatches.Patch(color='#e67e22', label='Stress'),
    mpatches.Patch(color='#e74c3c', label='Depression'),
    mpatches.Patch(color='#9b59b6', label='Cross-domain causal edge'),
]
ax.legend(handles=patches, loc='lower right', fontsize=11)

ax.set_title('PC Algorithm: Causal Structure of Academic Pressure Symptoms\n'+
             'Purple arrows = causal pathways between domains',
             fontweight='bold', fontsize=13)
ax.axis('off')
plt.tight_layout()
plt.savefig('fig6_pc_algorithm_network.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig6_pc_algorithm_network.png")

# ============================================================
# PATHWAY EXTRACTION AND CHARACTERIZATION
# Fulfills Sub-Objective 4 and strengthens for Q1
# ============================================================

import networkx as nx
import json
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from collections import Counter

# Load Bayesian Network edges
with open('bayesian_edges.json') as f:
    bn_edges = json.load(f)

G_bn = nx.DiGraph()
G_bn.add_edges_from(bn_edges)

print("=== PATHWAY EXTRACTION ===")
print(f"Nodes: {len(G_bn.nodes())}")
print(f"Edges: {len(G_bn.edges())}")

# ---- Extract ALL simple paths between domains ----
anxiety_nodes    = [n for n in G_bn.nodes() if n.startswith('A')]
stress_nodes     = [n for n in G_bn.nodes() if n.startswith('S')]
depression_nodes = [n for n in G_bn.nodes() if n.startswith('D')]

all_paths = []

# Anxiety → Depression paths
for src in anxiety_nodes:
    for tgt in depression_nodes:
        try:
            paths = list(nx.all_simple_paths(G_bn, src, tgt, cutoff=6))
            for p in paths:
                all_paths.append({
                    'path': p,
                    'length': len(p) - 1,
                    'source_domain': 'Anxiety',
                    'target_domain': 'Depression',
                    'path_str': ' → '.join(p)
                })
        except nx.NetworkXNoPath:
            pass

# Anxiety → Stress paths
for src in anxiety_nodes:
    for tgt in stress_nodes:
        try:
            paths = list(nx.all_simple_paths(G_bn, src, tgt, cutoff=4))
            for p in paths:
                all_paths.append({
                    'path': p,
                    'length': len(p) - 1,
                    'source_domain': 'Anxiety',
                    'target_domain': 'Stress',
                    'path_str': ' → '.join(p)
                })
        except nx.NetworkXNoPath:
            pass

# Stress → Depression paths
for src in stress_nodes:
    for tgt in depression_nodes:
        try:
            paths = list(nx.all_simple_paths(G_bn, src, tgt, cutoff=4))
            for p in paths:
                all_paths.append({
                    'path': p,
                    'length': len(p) - 1,
                    'source_domain': 'Stress',
                    'target_domain': 'Depression',
                    'path_str': ' → '.join(p)
                })
        except nx.NetworkXNoPath:
            pass

paths_df = pd.DataFrame(all_paths)
print(f"\nTotal paths found: {len(paths_df)}")
print(f"Anxiety→Depression: {len(paths_df[paths_df.source_domain=='Anxiety'][paths_df.target_domain=='Depression'])}")
print(f"Anxiety→Stress:     {len(paths_df[paths_df.source_domain=='Anxiety'][paths_df.target_domain=='Stress'])}")
print(f"Stress→Depression:  {len(paths_df[paths_df.source_domain=='Stress'][paths_df.target_domain=='Depression'])}")

# ---- Path Length Distribution ----
print("\nPath Length Distribution:")
print(paths_df['length'].value_counts().sort_index())

# ---- Most Common Intermediary Symptoms ----
intermediaries = []
for _, row in paths_df.iterrows():
    path = row['path']
    if len(path) > 2:
        for node in path[1:-1]:  # exclude start and end
            intermediaries.append(node)

intermediary_counts = Counter(intermediaries)
print("\nTop 10 Most Common Intermediary Symptoms:")
for node, count in intermediary_counts.most_common(10):
    domain = 'Anxiety' if node.startswith('A') else 'Stress' if node.startswith('S') else 'Depression'
    print(f"  {node} [{domain}]: appears in {count} pathways")

# ---- Top Anxiety→Depression Pathways ----
a2d = paths_df[(paths_df.source_domain=='Anxiety') &
               (paths_df.target_domain=='Depression')].sort_values('length')

print("\nTop 10 Anxiety→Depression Pathways (shortest first):")
for i, (_, row) in enumerate(a2d.head(10).iterrows()):
    print(f"  [{row['length']} steps] {row['path_str']}")

# ---- Critical Pathway to Suicidal Ideation ----
suicidal_paths = paths_df[paths_df['path'].apply(lambda p: 'D9_SuicidalThoughts' in p)]
print(f"\nPaths leading to D9_SuicidalThoughts: {len(suicidal_paths)}")
print("Critical suicidal ideation pathways:")
for _, row in suicidal_paths.sort_values('length').head(5).iterrows():
    print(f"  [{row['length']} steps] {row['path_str']}")

# ---- Visualization: Pathway Summary ----
fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# Path length histogram
paths_df['length'].hist(bins=range(1, 8), ax=axes[0],
                        color='#3498db', edgecolor='black', alpha=0.8)
axes[0].set_xlabel('Pathway Length (number of steps)', fontsize=12)
axes[0].set_ylabel('Number of Pathways', fontsize=12)
axes[0].set_title('Distribution of Symptom Pathway Lengths', fontweight='bold')

# Top intermediary symptoms
top_intermediaries = intermediary_counts.most_common(10)
nodes_i, counts_i = zip(*top_intermediaries)
colors_i = ['#3498db' if n.startswith('A') else '#e67e22' if n.startswith('S') else '#e74c3c'
            for n in nodes_i]
axes[1].barh(range(len(nodes_i)), counts_i, color=colors_i)
axes[1].set_yticks(range(len(nodes_i)))
axes[1].set_yticklabels(nodes_i, fontsize=10)
axes[1].set_xlabel('Frequency as Intermediary', fontsize=12)
axes[1].set_title('Most Common Intermediary Symptoms\nAcross All Pathways', fontweight='bold')
axes[1].invert_yaxis()

import matplotlib.patches as mpatches
legend = [
    mpatches.Patch(color='#3498db', label='Anxiety'),
    mpatches.Patch(color='#e67e22', label='Stress'),
    mpatches.Patch(color='#e74c3c', label='Depression'),
]
axes[1].legend(handles=legend)

plt.tight_layout()
plt.savefig('fig_pathway_analysis.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig_pathway_analysis.png")

# Save all paths
paths_df['path_str'].to_csv('all_pathways.csv', index=False)
print("Saved: all_pathways.csv")

# Summary table for paper
print("\n=== PATHWAY SUMMARY TABLE (for paper) ===")
summary = paths_df.groupby(['source_domain', 'target_domain']).agg(
    total_paths=('path_str', 'count'),
    mean_length=('length', 'mean'),
    min_length=('length', 'min'),
    max_length=('length', 'max')
).round(2)
print(summary)

"""#XGBOOST + SHAP EXPLAINABILITY"""

import xgboost as xgb
import shap
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics import classification_report, roc_auc_score, matthews_corrcoef
import matplotlib.pyplot as plt
import numpy as np

# ---- 7A: Binary Target — Severe Depression ----
# Severe + Moderately Severe = 49.7% of students
y = symptoms['Depression_Label'].isin(
    ['Severe Depression', 'Moderately Severe Depression']
).astype(int)

print(f"Target distribution:")
print(f"  Severe/Mod-Severe: {y.sum()} ({y.mean()*100:.1f}%)")
print(f"  Mild/Minimal:      {(1-y).sum()} ({(1-y).mean()*100:.1f}%)")

X_arr = X.values
X_train, X_test, y_train, y_test = train_test_split(
    X_arr, y, test_size=0.2, random_state=42, stratify=y
)

# ---- 7B: Train XGBoost ----
clf = xgb.XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss',
    verbosity=0
)
clf.fit(X_train, y_train)

# ---- 7C: Evaluate ----
y_pred  = clf.predict(X_test)
y_prob  = clf.predict_proba(X_test)[:, 1]

print("\n=== XGBoost Performance ===")
print(classification_report(y_test, y_pred))
print(f"AUC-ROC: {roc_auc_score(y_test, y_prob):.4f}")
print(f"MCC:     {matthews_corrcoef(y_test, y_pred):.4f}")

# 5-Fold Cross Validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_f1  = cross_val_score(clf, X_arr, y, cv=cv, scoring='f1')
cv_auc = cross_val_score(clf, X_arr, y, cv=cv, scoring='roc_auc')
print(f"\n5-Fold CV F1:  {cv_f1.mean():.4f} ± {cv_f1.std():.4f}")
print(f"5-Fold CV AUC: {cv_auc.mean():.4f} ± {cv_auc.std():.4f}")

# ---- 7D: SHAP Analysis ----
print("\nRunning SHAP analysis...")
explainer   = shap.TreeExplainer(clf)
shap_values = explainer.shap_values(X_test)

mean_shap = np.abs(shap_values).mean(axis=0)
shap_df   = pd.DataFrame({
    'symptom': SYMPTOM_COLS,
    'mean_shap': mean_shap,
    'domain': ['Anxiety' if s.startswith('A') else 'Stress' if s.startswith('S') else 'Depression'
               for s in SYMPTOM_COLS]
}).sort_values('mean_shap', ascending=False)

print("\nTop 15 SHAP Feature Importances:")
print(shap_df.head(15)[['symptom', 'domain', 'mean_shap']].to_string(index=False))

# ---- 7E: SHAP Bar Plot ----
colors = ['#d2f291' if d == 'Depression' else '#42dbb2' if d == 'Anxiety' else '#66de57'
          for d in shap_df['domain']]

fig, ax = plt.subplots(figsize=(12, 10))
bars = ax.barh(range(len(shap_df)), shap_df['mean_shap'], color=colors)
ax.set_yticks(range(len(shap_df)))
ax.set_yticklabels(shap_df['symptom'], fontsize=10)
ax.set_xlabel('Mean |SHAP Value|', fontsize=12)
ax.set_title('SHAP Feature Importance: Drivers of Severe Depression\n'
             'Among Bangladeshi Private University Students',
             fontweight='bold', fontsize=13)
ax.invert_yaxis()

import matplotlib.patches as mpatches
legend = [
    mpatches.Patch(color='#d2f291', label='Depression symptom'),
    mpatches.Patch(color='#42dbb2', label='Anxiety symptom'),
    mpatches.Patch(color='#66de57', label='Stress symptom'),
]
ax.legend(handles=legend, loc='lower right', fontsize=11)
plt.tight_layout()
plt.savefig('fig7_shap_importance.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig7_shap_importance.png")

# ---- 7F: SHAP Beeswarm Plot ----
fig, ax = plt.subplots(figsize=(14, 10))
shap.summary_plot(shap_values, X_test,
                  feature_names=SYMPTOM_COLS,
                  show=False)
plt.title('SHAP Beeswarm: Direction and Magnitude of Each Symptom',
          fontweight='bold', fontsize=12)
plt.tight_layout()
plt.savefig('fig8_shap_beeswarm.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig8_shap_beeswarm.png")

# Save results
shap_df.to_csv('shap_results.csv', index=False)
print("Saved: shap_results.csv")

"""#Moderation Analysis"""

# Does CGPA or Scholarship Status change the symptom pathways?

from scipy import stats
import matplotlib.pyplot as plt
import numpy as np

# ---- 8A: CGPA Moderation ----
print("=== CGPA MODERATION ANALYSIS ===\n")

cgpa_groups = {
    'High (3.80-4.00)':   symptoms[symptoms['CGPA'] == '3.80 - 3.79'],
    'Mid (3.00-3.39)':    symptoms[symptoms['CGPA'] == '3.00 - 3.39'],
    'Low (<2.50)':        symptoms[symptoms['CGPA'] == 'Below 2.50'],
}

# Correct CGPA column values
print("CGPA value counts:")
print(symptoms['CGPA'].value_counts())

cgpa_groups = {
    'High (3.80-4.00)':   symptoms[symptoms['CGPA'] == '3.80 - 4.00'],
    'Mid (3.00-3.79)':    symptoms[symptoms['CGPA'].isin(['3.00 - 3.39', '3.40 - 3.79'])],
    'Low (<2.50)':        symptoms[symptoms['CGPA'] == 'Below 2.50'],
}

results_cgpa = []
for group_name, group_df in cgpa_groups.items():
    group_X = group_df[SYMPTOM_COLS]
    anxiety_mean    = group_X[ANXIETY_COLS].mean().mean()
    stress_mean     = group_X[STRESS_COLS].mean().mean()
    depression_mean = group_X[DEPRESSION_COLS].mean().mean()
    severe_pct      = (group_df['Depression_Label'].isin(
                        ['Severe Depression', 'Moderately Severe Depression'])).mean() * 100
    results_cgpa.append({
        'Group': group_name,
        'N': len(group_df),
        'Anxiety Mean': round(anxiety_mean, 3),
        'Stress Mean':  round(stress_mean, 3),
        'Depression Mean': round(depression_mean, 3),
        'Severe Depression %': round(severe_pct, 1)
    })
    print(f"{group_name} (n={len(group_df)}): Anxiety={anxiety_mean:.3f}, Stress={stress_mean:.3f}, Depression={depression_mean:.3f}, Severe Dep={severe_pct:.1f}%")

# Statistical test: ANOVA across CGPA groups for depression
high_dep = cgpa_groups['High (3.80-4.00)'][DEPRESSION_COLS].mean(axis=1)
low_dep  = cgpa_groups['Low (<2.50)'][DEPRESSION_COLS].mean(axis=1)
t_stat, p_val = stats.ttest_ind(high_dep, low_dep)
print(f"\nHigh vs Low CGPA depression: t={t_stat:.3f}, p={p_val:.4f}")
if p_val < 0.05:
    print("SIGNIFICANT: Low CGPA students have significantly worse depression")

# ---- 8B: Scholarship Moderation ----
print("\n=== SCHOLARSHIP MODERATION ANALYSIS ===\n")

with_schol    = symptoms[symptoms['Scholarship'] == 'Yes']
without_schol = symptoms[symptoms['Scholarship'] == 'No']

for label, grp in [('With Scholarship', with_schol), ('Without Scholarship', without_schol)]:
    grp_X = grp[SYMPTOM_COLS]
    print(f"{label} (n={len(grp)}):")
    print(f"  Anxiety:    {grp_X[ANXIETY_COLS].mean().mean():.3f}")
    print(f"  Stress:     {grp_X[STRESS_COLS].mean().mean():.3f}")
    print(f"  Depression: {grp_X[DEPRESSION_COLS].mean().mean():.3f}")
    severe_pct = (grp['Depression_Label'].isin(
                    ['Severe Depression', 'Moderately Severe Depression'])).mean()*100
    print(f"  Severe Depression: {severe_pct:.1f}%")

# T-test
t_s, p_s = stats.ttest_ind(
    with_schol[DEPRESSION_COLS].mean(axis=1),
    without_schol[DEPRESSION_COLS].mean(axis=1)
)
print(f"\nScholarship vs No-scholarship depression: t={t_s:.3f}, p={p_s:.4f}")

# Effect size (Cohen's d)
def cohen_d(a, b):
    pooled_std = np.sqrt((np.std(a, ddof=1)**2 + np.std(b, ddof=1)**2) / 2)
    return (np.mean(a) - np.mean(b)) / pooled_std

d = cohen_d(with_schol[DEPRESSION_COLS].mean(axis=1),
            without_schol[DEPRESSION_COLS].mean(axis=1))
print(f"Cohen's d: {d:.4f} ({'small' if abs(d)<0.5 else 'medium' if abs(d)<0.8 else 'large'} effect)")

# ---- 8C: Visualization ----
fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# CGPA moderation plot
cgpa_labels  = ['High\n(3.80-4.00)', 'Mid\n(3.00-3.79)', 'Low\n(<2.50)']
anxiety_vals = [cgpa_groups[g][ANXIETY_COLS].mean().mean() for g in cgpa_groups]
stress_vals  = [cgpa_groups[g][STRESS_COLS].mean().mean() for g in cgpa_groups]
dep_vals     = [cgpa_groups[g][DEPRESSION_COLS].mean().mean() for g in cgpa_groups]

x = np.arange(len(cgpa_labels))
w = 0.25
axes[0].bar(x - w, anxiety_vals, w, label='Anxiety', color='#3498db', alpha=0.8)
axes[0].bar(x,     stress_vals,  w, label='Stress',  color='#10597d', alpha=0.8)
axes[0].bar(x + w, dep_vals,     w, label='Depression', color='#0e285c', alpha=0.8)
axes[0].set_xticks(x)
axes[0].set_xticklabels(cgpa_labels)
axes[0].set_title('Symptom Severity by CGPA Group\n(Moderation Analysis)',
                  fontweight='bold')
axes[0].set_ylabel('Mean Symptom Score')
axes[0].legend()

# Scholarship moderation
schol_labels = ['With Scholarship', 'Without Scholarship']
for idx, (label, grp) in enumerate([('With', with_schol), ('Without', without_schol)]):
    grp_X = grp[SYMPTOM_COLS]
    axes[1].bar([idx - 0.25], [grp_X[ANXIETY_COLS].mean().mean()], 0.25,
                color='#3d1d16', alpha=0.8, label='Anxiety' if idx == 0 else "")
    axes[1].bar([idx],         [grp_X[STRESS_COLS].mean().mean()], 0.25,
                color='#3b0207', alpha=0.8, label='Stress' if idx == 0 else "")
    axes[1].bar([idx + 0.25],  [grp_X[DEPRESSION_COLS].mean().mean()], 0.25,
                color='#e74c3c', alpha=0.8, label='Depression' if idx == 0 else "")

axes[1].set_xticks([0, 1])
axes[1].set_xticklabels(schol_labels)
axes[1].set_title('Symptom Severity by Scholarship Status\n(Moderation Analysis)',
                  fontweight='bold')
axes[1].set_ylabel('Mean Symptom Score')
axes[1].legend()

plt.tight_layout()
plt.savefig('fig9_moderation_analysis.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig9_moderation_analysis.png")

# ============================================================
# NETWORK COMPARISON BY CGPA GROUP
# Fulfills Sub-Objective 5 properly
# ============================================================

from scipy import stats
import networkx as nx
import matplotlib.pyplot as plt

# Split into two CGPA groups
high_cgpa = symptoms[symptoms['CGPA'] == '3.80 - 4.00'][SYMPTOM_COLS]
low_cgpa  = symptoms[symptoms['CGPA'] == 'Below 2.50'][SYMPTOM_COLS]
mid_cgpa  = symptoms[symptoms['CGPA'].isin(['3.00 - 3.39', '3.40 - 3.79'])][SYMPTOM_COLS]

print(f"High CGPA (3.80-4.00): n={len(high_cgpa)}")
print(f"Mid CGPA (3.00-3.79):  n={len(mid_cgpa)}")
print(f"Low CGPA (<2.50):      n={len(low_cgpa)}")

def build_network(data, threshold=0.30):
    corr = data.corr(method='spearman')
    G = nx.Graph()
    G.add_nodes_from(SYMPTOM_COLS)
    for i, c1 in enumerate(SYMPTOM_COLS):
        for j, c2 in enumerate(SYMPTOM_COLS):
            if i < j and abs(corr.loc[c1,c2]) > threshold:
                G.add_edge(c1, c2, weight=abs(corr.loc[c1,c2]))
    return G, corr

G_high, corr_high = build_network(high_cgpa)
G_mid,  corr_mid  = build_network(mid_cgpa)
G_low,  corr_low  = build_network(low_cgpa)

print("\n=== NETWORK METRICS BY CGPA GROUP ===")
print(f"{'Metric':<35} {'High':>10} {'Mid':>10} {'Low':>10}")
print("-" * 67)

metrics = {
    'Total edges':          [G_high.number_of_edges(), G_mid.number_of_edges(), G_low.number_of_edges()],
    'Mean edge weight':     [
        sum(d['weight'] for _,_,d in G_high.edges(data=True))/max(G_high.number_of_edges(),1),
        sum(d['weight'] for _,_,d in G_mid.edges(data=True))/max(G_mid.number_of_edges(),1),
        sum(d['weight'] for _,_,d in G_low.edges(data=True))/max(G_low.number_of_edges(),1)
    ],
    'Cross-domain edges':   [
        sum(1 for u,v in G_high.edges() if u[0]!=v[0]),
        sum(1 for u,v in G_mid.edges() if u[0]!=v[0]),
        sum(1 for u,v in G_low.edges() if u[0]!=v[0])
    ],
    'Mean node degree':     [
        sum(dict(G_high.degree()).values())/len(G_high.nodes()),
        sum(dict(G_mid.degree()).values())/len(G_mid.nodes()),
        sum(dict(G_low.degree()).values())/len(G_low.nodes())
    ],
    'Avg clustering coeff': [
        nx.average_clustering(G_high),
        nx.average_clustering(G_mid),
        nx.average_clustering(G_low)
    ],
}

for metric, vals in metrics.items():
    print(f"  {metric:<33} {vals[0]:>10.3f} {vals[1]:>10.3f} {vals[2]:>10.3f}")

# Statistical test: edge weight distributions
_, p_high_low = stats.ttest_ind(
    [d['weight'] for _,_,d in G_high.edges(data=True)],
    [d['weight'] for _,_,d in G_low.edges(data=True)]
)
print(f"\nHigh vs Low CGPA edge weight difference: p={p_high_low:.4f}")

# Most central symptom per group
for label, G in [('High CGPA', G_high), ('Mid CGPA', G_mid), ('Low CGPA', G_low)]:
    strength = {n: sum(d['weight'] for _,_,d in G.edges(n,data=True)) for n in G.nodes()}
    top_node = max(strength, key=strength.get)
    print(f"{label} most central symptom: {top_node} (strength={strength[top_node]:.3f})")

# Visualization
fig, axes = plt.subplots(1, 3, figsize=(20, 7))

for ax, (label, G_sub, corr_sub) in zip(axes, [
    ('High CGPA\n(n=237)', G_high, corr_high),
    ('Mid CGPA\n(n=1123)', G_mid, corr_mid),
    ('Low CGPA\n(n=81)', G_low, corr_low)
]):
    pos = {}
    for i, n in enumerate([x for x in SYMPTOM_COLS if x.startswith('A')]):
        pos[n] = (-3, i * 1.2 - 4)
    for i, n in enumerate([x for x in SYMPTOM_COLS if x.startswith('S')]):
        pos[n] = (0, i * 1.2 - 5)
    for i, n in enumerate([x for x in SYMPTOM_COLS if x.startswith('D')]):
        pos[n] = (3, i * 1.2 - 4)

    node_colors = ['#3498db' if n.startswith('A') else
                   '#e67e22' if n.startswith('S') else '#e74c3c'
                   for n in G_sub.nodes()]

    within = [(u,v) for u,v in G_sub.edges() if u[0]==v[0]]
    cross  = [(u,v) for u,v in G_sub.edges() if u[0]!=v[0]]

    nx.draw_networkx_edges(G_sub, pos, edgelist=within, width=1, alpha=0.2,
                           edge_color='gray', ax=ax)
    nx.draw_networkx_edges(G_sub, pos, edgelist=cross, width=2.5, alpha=0.8,
                           edge_color='#9b59b6', ax=ax)
    nx.draw_networkx_nodes(G_sub, pos, node_color=node_colors,
                           node_size=400, alpha=0.9, ax=ax)
    nx.draw_networkx_labels(G_sub, pos, font_size=6, ax=ax)
    ax.set_title(f'{label}\nEdges={G_sub.number_of_edges()}, '
                 f'Cross={sum(1 for u,v in G_sub.edges() if u[0]!=v[0])}',
                 fontweight='bold')
    ax.axis('off')

plt.suptitle('Symptom Network Comparison by CGPA Group\n(Purple = cross-domain bridges)',
             fontweight='bold', fontsize=13)
plt.tight_layout()
plt.savefig('fig_cgpa_network_comparison.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig_cgpa_network_comparison.png")

"""#Pathway profiling"""

# Assign each student to a risk pathway type


from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
import numpy as np

# ---- 9A: Define the 5 Pathways from Bayesian Network ----
# Based on discovered causal chains
PATHWAYS = {
    'P1_AcademicAnxiety_StressCascade': {
        'key_nodes': ['A4_Irritated', 'S2_CantControl', 'S4_CantCope', 'S10_DifficultiesPiling'],
        'description': 'Academic irritability → loss of control → inability to cope → overwhelm',
        'entry_point': 'A4_Irritated',
        'endpoint': 'S10_DifficultiesPiling'
    },
    'P2_Worry_StressAmplification': {
        'key_nodes': ['A1_Nervous', 'S3_NervousStressed', 'S4_CantCope', 'A5_WorriedTooMuch'],
        'description': 'Nervousness → stress amplification → inability to cope',
        'entry_point': 'A1_Nervous',
        'endpoint': 'S4_CantCope'
    },
    'P3_AcademicPerformance_Depression': {
        'key_nodes': ['S8_PerformanceOnTop', 'D6_FeelingBad', 'D2_FeelingDown', 'D4_LowEnergy'],
        'description': 'Poor academic performance perception → self-blame → hopelessness → fatigue',
        'entry_point': 'S8_PerformanceOnTop',
        'endpoint': 'D4_LowEnergy'
    },
    'P4_Restlessness_PhysicalDepression': {
        'key_nodes': ['A6_Restless', 'D4_LowEnergy', 'D3_SleepProblems', 'D5_PoorAppetite'],
        'description': 'Restlessness → energy drain → sleep disruption → appetite problems',
        'entry_point': 'A6_Restless',
        'endpoint': 'D5_PoorAppetite'
    },
    'P5_SelfEfficacy_SuicidalRisk': {
        'key_nodes': ['S5_Confident', 'S6_GoingMyWay', 'D6_FeelingBad', 'D9_SuicidalThoughts'],
        'description': 'Loss of confidence → life not going well → self-blame → suicidal ideation',
        'entry_point': 'S5_Confident',
        'endpoint': 'D9_SuicidalThoughts',
        'critical': True
    }
}

# ---- 9B: Score Each Student on Each Pathway ----
pathway_scores = pd.DataFrame(index=symptoms.index)

for pathway_name, pathway_info in PATHWAYS.items():
    nodes = pathway_info['key_nodes']
    # Pathway score = mean of key node scores
    pathway_scores[pathway_name] = X[nodes].mean(axis=1)

print("Pathway Score Statistics:")
print(pathway_scores.describe().round(3))

# ---- 9C: Assign Dominant Pathway ----
pathway_scores['dominant_pathway'] = pathway_scores[list(PATHWAYS.keys())].idxmax(axis=1)
print("\nPathway Distribution:")
print(pathway_scores['dominant_pathway'].value_counts())

# ---- 9D: Cluster Students (K-Means) ----
print("\n=== K-MEANS CLUSTERING (Pathway-Based) ===")
scaler = StandardScaler()
X_pathway = scaler.fit_transform(pathway_scores[list(PATHWAYS.keys())])

# Find optimal k
sil_scores = []
for k in range(2, 7):
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_pathway)
    sil = silhouette_score(X_pathway, labels)
    sil_scores.append(sil)
    print(f"k={k}: Silhouette={sil:.4f}")

best_k = np.argmax(sil_scores) + 2
print(f"\nOptimal k: {best_k}")

km_final = KMeans(n_clusters=best_k, random_state=42, n_init=10)
symptoms['pathway_cluster'] = km_final.fit_predict(X_pathway)

# ---- 9E: Profile Each Cluster ----
print("\n=== CLUSTER PROFILES ===")
for cluster in range(best_k):
    mask = symptoms['pathway_cluster'] == cluster
    cluster_df = symptoms[mask]
    cluster_X  = X[mask]
    print(f"\nCluster {cluster} (n={mask.sum()}):")
    print(f"  Dominant pathway: {pathway_scores[mask]['dominant_pathway'].mode()[0]}")
    print(f"  Anxiety mean:     {cluster_X[ANXIETY_COLS].mean().mean():.3f}")
    print(f"  Stress mean:      {cluster_X[STRESS_COLS].mean().mean():.3f}")
    print(f"  Depression mean:  {cluster_X[DEPRESSION_COLS].mean().mean():.3f}")
    sev_pct = cluster_df['Depression_Label'].isin(
                ['Severe Depression', 'Moderately Severe Depression']).mean()*100
    print(f"  Severe Depression: {sev_pct:.1f}%")

# ---- 9F: Pathway Risk Visualization ----
fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# Pathway score distribution
pathway_scores[list(PATHWAYS.keys())].boxplot(ax=axes[0], vert=False)
axes[0].set_title('Distribution of Pathway Scores\nAcross All Students',
                   fontweight='bold')
axes[0].set_xlabel('Mean Pathway Score')
short_names = ['P1: Anxiety→Stress', 'P2: Worry→Stress',
               'P3: Performance→Dep', 'P4: Restless→Physical', 'P5: Efficacy→Suicidal']
axes[0].set_yticklabels(short_names)

# P5 critical pathway — suicidal risk profiling
p5_scores = pathway_scores['P5_SelfEfficacy_SuicidalRisk']
p5_threshold = p5_scores.mean() + 1.5 * p5_scores.std()
high_risk = (p5_scores > p5_threshold).sum()
axes[1].hist(p5_scores, bins=30, color='#076159', alpha=0.7, edgecolor='black')
axes[1].axvline(x=p5_threshold, color='darkred', linestyle='--', linewidth=2,
                label=f'High Risk Threshold\n(n={high_risk}, {high_risk/len(symptoms)*100:.1f}%)')
axes[1].set_title('CRITICAL PATHWAY P5: Self-Efficacy → Suicidal Risk\nScore Distribution',
                   fontweight='bold', color='darkred')
axes[1].set_xlabel('P5 Pathway Score')
axes[1].set_ylabel('Number of Students')
axes[1].legend()

plt.tight_layout()
plt.savefig('fig10_pathway_profiles.png', dpi=300, bbox_inches='tight')
plt.show()
print("Saved: fig10_pathway_profiles.png")

print(f"\nCRITICAL: {high_risk} students ({high_risk/len(symptoms)*100:.1f}%) are HIGH RISK on the suicidal ideation pathway")
print("These students require immediate counseling intervention")

# Save pathway assignments
pathway_scores['Depression_Label'] = symptoms['Depression_Label'].values
pathway_scores['CGPA'] = symptoms['CGPA'].values
pathway_scores.to_csv('pathway_profiles.csv', index=False)
print("Saved: pathway_profiles.csv")